// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
// changed 24-05-2023
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace H4_Software_test.Models;
/// <summary>
/// OBS OBS OBS. Denne context må ikke bruges da det er et brud på sikkerhed. Skal slettes ved lejlighed
/// </summary>
public partial class aspnetH4Softwaretest3a56d5607b184dc6bb4f36cb9fd57e40Context : DbContext
{
    public aspnetH4Softwaretest3a56d5607b184dc6bb4f36cb9fd57e40Context(DbContextOptions<aspnetH4Softwaretest3a56d5607b184dc6bb4f36cb9fd57e40Context> options)
        : base(options)
    {
    }

    public virtual DbSet<TextFiles> TextFiles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TextFiles>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__TextFile__3214EC078D5EF14F");

            entity.Property(e => e.FileName)
                .IsRequired()
                .HasMaxLength(256);
            entity.Property(e => e.FilePath)
                .IsRequired()
                .HasMaxLength(1024);
            entity.Property(e => e.UserId).HasMaxLength(450);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);

    /// <summary>
    /// Sets database state to the modified state.
    /// I dont know if this method should be part of the implemented datacontext or somewhere else.
    /// </summary>
    /// <typeparam name="TEntity"></typeparam>
    /// <param name="entity"></param>
    public TEntity SetModified<TEntity>(TEntity entity) where TEntity : class
    {
        Entry(entity).State = EntityState.Modified;
        return entity;
    }
}