// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace H4_Software_test.Models;

public partial class TextFiles
{
    public int Id { get; set; }

    public string FileName { get; set; }

    public string FilePath { get; set; }

    public string UserId { get; set; }
}